require("express-async-errors")
const express = require("express")
const { initDB } = require("./src/init/initDB")
const { initErrorMiddleware } = require("./src/init/initErrorMiddleware")
const cors = require("cors")

const { initListen } = require("./src/init/initListen")
const { initMiddleware } = require("./src/init/initMiddleware")
const { initRoutes } = require("./src/init/initRoutes")
const { checkConfigs } = require("./src/init/initConfig")

const app = express()
app.use(cors())
checkConfigs()
initMiddleware(app)
initDB()
initRoutes(app)
initListen(app)
initErrorMiddleware(app)
